#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

commit_msg=$(cat "$1")

RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\033[1m'
NC='\033[0m' # No Color

if [[ $commit_msg =~ ^WTH-[0-9]+: ]]; then
  echo "${GREEN}${BOLD}Good commit message.${NC}"
else
  echo "${RED}${BOLD}Start commit message with 'WTH-<ticket_number>:' (e.g., 'WTH-123: Add new feature')${NC}"
  exit 1
fi

# Run linting
yarn lint

if [ $? -ne 0 ]; then
  echo "${RED}${BOLD}Fix linting errors.${NC}"
  exit 1
fi
